name: Validate Branch Name

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate_branch_name:
    runs-on: ubuntu-latest
    name: Ensure branch name follows allowed patterns

    steps:
      - name: Check branch name format
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Checking branch name: $BRANCH_NAME"

          # Define allowed patterns
          if [[ ! "$BRANCH_NAME" =~ ^(main|develop|feat/.+|fix/.+|chore/.+|docs/.+|ci/.+|test/.+|style/.+|refactor/.+|build/.+)$ ]]; then
            echo "::error :: The branch name '$BRANCH_NAME' is invalid."
            echo "::error :: Use one of the allowed patterns:"
            echo "::error ::    - feat/feature-name"
            echo "::error ::    - fix/bug-description"
            echo "::error ::    - chore/minor-adjustment"
            echo "::error ::    - docs/readme-update"
            echo "::error ::    - ci/pipeline-changes"
            echo "::error ::    - test/unit-tests"
            echo "::error ::    - style/formatting"
            echo "::error ::    - refactor/internal-improvements"
            echo "::error ::    - build/build-adjustments"
            exit 1
          fi

          echo "Branch name '$BRANCH_NAME' is valid."
